board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.BoardIndex.as_view(), name='index'),
    path('detail/<str:slug>/', views.BoardDetail.as_view(), name='detail'),
    path('detail/<str:slug>/comment/create/', views.comment_create, name='comment_create'),
    path('detail/<str:slug>/comment/', views.CommentListView.as_view(), name='comment'),
    path('detail/<str:slug>/comment/create/', views.comment_create, name='comment_create'),
    path('detail/<str:slug>/comment/update/<int:pk>/', views.comment_update, name='comment_update'),
    path('detail/<str:slug>/comment/delete/<int:pk>/', views.comment_delete, name='comment_delete'),
    path('like/', views.like, name='like'),
    path('post/new/', views.BoardCreateV.as_view(), name='post_add'),
    path('post/edit/<int:pk>/', views.BoardUpdateV.as_view(), name='post_edit'),
    path('post/delete/<int:pk>/', views.BoardDeleteV.as_view(), name='post_delete'),
]

helpers/urls.py
from django.urls import path
from . import views

app_name='helpers'
urlpatterns = [
    path('search/', views.search_word, name='search'),
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from store.models import Store
from board.models import UserBoard

class HomePageView(TemplateView):

    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['store_list'] = Store.objects.filter(category='restaurant')[:1] | \
                                Store.objects.filter(category='bar')[:1] | \
                                Store.objects.filter(category='cafe')[:1]

        return context

urlpatterns = [
    path('board/', include('board.urls')),
    path('store/', include('store.urls')),
    path('helpers/', include('helpers.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomePageView.as_view(), name='home'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
]

if settings.DEBUG:
    if settings.DEBUG:
        import debug_toolbar
        urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.StoreIndexView.as_view(), name='index'),
    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),
    path('like/', views.like, name='like'),
    path('detail/<str:slug>/', views.StoreDetailView.as_view(), name='detail'),
    path('detail/<str:slug>/comment/', views.CommentListView.as_view(), name='comment'),
    path('detail/<str:slug>/comment/create/', views.comment_create, name='comment_create'),
    path('detail/<str:slug>/comment/update/<int:pk>/', views.comment_update, name='comment_update'),
    path('detail/<str:slug>/comment/delete/<int:pk>/', views.comment_delete, name='comment_delete'),
    path('create/', views.StoreCreateView.as_view(), name='store_add'),
    path('edit/<int:pk>/', views.StoreEditView.as_view(), name='store_edit'),
    path('delete/<int:pk>/', views.StoreDeleteView.as_view(), name='store_delete'),
]

store/models.py
from django.db import models
from django.shortcuts import reverse
from taggit.managers import TaggableManager
from django.utils.text import slugify
from django.conf import settings


class BaseModel(models.Model):
    created_dt = models.DateTimeField(auto_now_add=True)
    modified_dt = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Store(BaseModel):
    CATEGORIES = (
        ('restaurant', '음식집'),
        ('bar', '술집'),
        ('cafe', '카페'),
    )
    name = models.CharField(max_length=50, verbose_name="가게명", unique=True)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for alias')
    location = models.CharField(max_length=100, blank=True, verbose_name="위치")
    phone_number = models.CharField(max_length=30, blank=True, verbose_name="연락처")
    description = models.TextField(blank=True, verbose_name="설명")
    store_image = models.ImageField(blank=True, upload_to="store/store_pic")
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_stores')
    like_count = models.PositiveIntegerField(default=0)
    tags = TaggableManager(blank=True)
    category = models.CharField(max_length=10, choices=CATEGORIES)
    running_time = models.CharField(max_length=30, blank=True, verbose_name='영업시간')

    class Meta:
        verbose_name = '가게'
        verbose_name_plural = '가게'
        ordering = ['-like_count', 'name']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('store:detail', args=[self.slug])


class Menu(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE, verbose_name="가게명")
    name = models.CharField(max_length=50, verbose_name="메뉴")
    description = models.CharField(max_length=50, blank=True, verbose_name="설명")
    food_image = models.ImageField(blank=True, upload_to="store/menu_pic")

    class Meta:
        verbose_name = '메뉴'
        verbose_name_plural = '메뉴'

    def __str__(self):
        return "{} - {}".format(self.store, self.name)


class Comment(BaseModel):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return f'{self.store} - {self.writer}'

    class Meta:
        verbose_name = '댓글'
        verbose_name_plural = '댓글'

store/forms.py
from django import forms
from .models import Store, Menu, Comment
from django.forms import inlineformset_factory

MenuInlineFormSet = inlineformset_factory(Store, Menu,
                                          fields=['name', 'description', 'food_image'],
                                          extra=2)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'id': 'inputComment', 'rows': '3', 'style': 'resize:none;'}),
        }

store/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from .models import Store, Comment
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormMixin
from .forms import MenuInlineFormSet, CommentForm
from mysite.views import AdminOnlyMixin
from django.conf import settings
import json


class StoreIndexView(ListView):
    template_name = 'store/index.html'
    context_object_name = "store_list"
    paginate_by = 10

    def get_queryset(self):
        return Store.objects.prefetch_related('menu_set').prefetch_related('like_users').all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5  # Display only 5 page numbers
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1
        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        return context


class CategoryView(ListView):
    template_name = 'store/index.html'
    context_object_name = 'store_list'
    paginate_by = 10

    def get_queryset(self):
        return Store.objects.filter(category=self.kwargs['category'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5  # Display only 5 page numbers
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1
        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        return context


@login_required
def like(request):
    pk = request.GET.get('pk', None)
    store = get_object_or_404(Store, pk=pk)

    if request.user in store.like_users.all():
        store.like_users.remove(request.user)
        store.like_count -= 1
        store.save()
        message = False
    else:
        store.like_users.add(request.user)
        store.like_count += 1
        store.save()
        message = True
    context = {
        'like_count': store.like_users.count(),
        'message': message,
        'nickname': request.user.nickname
    }
    return HttpResponse(json.dumps(context), content_type="application/json")
    # return redirect(store.get_absolute_url())


class CommentListView(ListView):
    model = Comment
    paginate_by = 5
    template_name = '_comment_list.html'
    context_object_name = 'comment_list'

    def get_queryset(self):
        store = get_object_or_404(Store, slug=self.kwargs['slug'])
        return store.comment_set.all()

    def get_context_data(self, *args, **kwargs):
        store = get_object_or_404(Store, slug=self.kwargs['slug'])
        context = super().get_context_data(*args, **kwargs)
        paginator = context['paginator']
        page_numbers_range = 5  # Display only 5 page numbers
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1
        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        context['store'] = store
        return context


@login_required
def comment_create(request, slug):
    if not request.user.is_authenticated:
        return JsonResponse({'authenticated': False})
    store = get_object_or_404(Store, slug=slug)
    form = CommentForm(request.POST)
    if form.is_valid():
        form.instance.writer = request.user
        form.instance.store = store
        form.save()
    paginator = Paginator(store.comment_set.all(), 5)
    last_page = paginator.num_pages
    return JsonResponse({'last_page': last_page, 'authenticated': True})


@login_required
def comment_update(request, slug, pk):
    store = get_object_or_404(Store, slug=slug)
    comment = store.comment_set.get(pk=pk)
    if comment.writer == request.user:
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save()
            html = render_to_string('_comment_update.html', {'store':store, 'comment': comment} )
            return JsonResponse({'is_updated': True, 'html': html})


@login_required
def comment_delete(request, slug, pk):
    store = get_object_or_404(Store, slug=slug)
    comment = store.comment_set.get(pk=pk)
    if comment.writer == request.user:
        comment.delete()
    return JsonResponse({'is_deleted': True})


class StoreDetailView(FormMixin, DetailView):
    model = Store
    template_name = 'store/store_detail.html'
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        context['comments'] = self.object.comment_set.all()
        context['KAKAO_JAVASCRIPT'] = settings.KAKAO_JAVASCRIPT
        return context


class StoreCreateView(AdminOnlyMixin, CreateView):
    model = Store
    fields = ['category', 'name', 'location', 'phone_number', 'description', 'store_image', 'tags', 'running_time']
    initial = {'slug': 'auto-filling-do-not-input'}
    success_url = reverse_lazy('store:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = MenuInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = MenuInlineFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))


class StoreEditView(AdminOnlyMixin, UpdateView):
    model = Store
    fields = ['category', 'name', 'location', 'phone_number', 'description', 'store_image', 'tags', 'running_time']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = MenuInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = MenuInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))


class StoreDeleteView(AdminOnlyMixin, DeleteView):
    model = Store
    success_url = reverse_lazy('store:index')

store/templates/store/index.html
{% extends "base.html" %}
{% load static %}
{% load sorl_thumbnail %}

{% block content %}
<div class="inner">
    <div class="row">
        <div class="col-sm-11">
            <a href="{% url 'store:index' %}"><h2 class="title">가게 소개</h2></a>
            <button class="btn btn-outline-primary" onclick="location.href='{% url 'store:index' %}'">전체보기</button>
            <button class="btn btn-outline-primary" onclick="location.href='{% url 'store:category' 'restaurant' %}'">음식집</button>
            <button class="btn btn-outline-primary" onclick="location.href='{% url 'store:category' 'bar' %}'">술집</button>
            <button class="btn btn-outline-primary" onclick="location.href='{% url 'store:category' 'cafe' %}'">카페</button>
            {% if user.is_staff %}
            <button type="button" class='btn btn-primary float-right mb-1' onclick="location.href='{% url 'store:store_add' %}'">가게글 작성</button>
            {% endif %}
        </div>
    </div>
    <div class="row">
      {% for store in store_list %}
      <div class="col-md-12">
      <div class="card">
          <a href="{{ store.get_absolute_url }}">
            {% for menu in store.menu_set.all %}
                {% if forloop.first %}
                    <div class="thumb">
                  {% thumbnail menu.food_image "370x250" crop="center" as im %}
                    {% if im.url %}
                        <img class="center-croping" src="{{ im.url }}" alt="">
                    {% else %}
                        <img class="center-croping" src="{% static 'img/alt_image.png' %}" style="width:100%; height: 255px;">>
                    {% endif %}
                  {% endthumbnail %}
                    </div>
                {% endif %}
            {% endfor %}
          </a>
          <div class="card-body">
              <span style="float: right;"><button post-id="{{ store.pk }}" class="btn store-like">
                {% if user in store.like_users.all %}
                  <i id="like-heart-{{ store.pk }}" class="fas fa-heart fa-2x"></i></button>
                {% else %}
                  <i id="like-heart-{{ store.pk }}" class="far fa-heart fa-2x"></i></button>
                {% endif %}</button>
                <p id="count-{{ store.pk }}" style="text-align: center">{{ store.like_users.count }}개</p>
              </span>
            <a class="h2 text-dark" href="{{ store.get_absolute_url }}">{{ forloop.counter0|add:page_obj.start_index }}. {{ store.name }}</a>
            <address>{{ store.location }}</address>
            <p class="card-text" style="position: static;">{{ store.description }}</p>
            <a href="{{ store.get_absolute_url }}" class="text-muted" style="position: absolute; right:20px; bottom:40px;">{{ store.name }} 더보기 ></a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
</div>
<div class="row mt-5">
    <div class="col board-footer">
        <div class="d-flex justify-content-center">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><span>Prev</span></a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#"><span>Prev</span></a>
                        </li>
                    {% endif %}

                    {% for page in page_range %}
                        <li class="page-item {% if page == page_obj.number %}active{% endif %}">
                            <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                        </li>
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}"><span>Next</span></a>
                        </li>
                    {% else %}
                        <li {% if not page_obj.has_next %}class="page-item disabled"{% endif %}>
                            <a class="page-link" href="#"><span>Next</span></a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}
{% block extra-script %}
<script>
    var MyGlobal = {
        url: "{% url 'store:like' %}",
    }
</script>
<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
{% endblock %}

store/templates/store/index2.html
{% extends "base.html" %}

{% block content %}
{% for store in store_list %}
    <ul>
        {% for menu in store.menu_set.all %}
            <li>{{menu}}</li>
            {% if forloop.first %}
                <img class="card-img-top" src="{{ im.url }}" alt="">
            {% endif %}
        {% endfor %}
    </ul>
{% endfor %}
{% endblock %}

store/templates/store/store_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form action="." method="post">
    {% csrf_token %}
    <div class="alert alert-danger">"{{ object }}"게시글을 삭제하겠습니까?</div>
    <button type="submit" class="btn btn-danger">삭제하기</button>
    <button type="reset" class="btn btn-danger" onclick="history.back()">취소하기</button>
</form>
{% endblock %}

store/templates/store/store_detail.html
{% extends "base.html" %}
{% load static %}
{% load sorl_thumbnail %}
{% block content %}
    {% if user.is_staff %}
        <button class="btn btn-primary" onclick="location.href='{% url 'store:store_edit' store.pk %}'">수정</button>
        <button class="btn btn-primary" onclick="location.href='{% url 'store:store_delete' store.pk %}'">삭제</button>
    {% endif %}
    <div class="board">
        <div class="row board-header">
            <div class="col-sm-12">
                <div class="float-right text-center">
                    <button post-id="{{ store.pk }}" class="btn store-like">
                        {% if user in store.like_users.all %}
                            <i id="like-heart-{{ store.pk }}" class="fas fa-heart fa-2x"></i></button>
                        {% else %}
                            <i id="like-heart-{{ store.pk }}" class="far fa-heart fa-2x"></i></button>
                        {% endif %}
                    <br>
                    <span id="count-{{ store.pk }}">{{ store.like_users.count }}개</span>
                    <span id="like-user-{{ store.pk }}"></span>
                </div>
                <div class="h3">{{ store.name }}</div>
            </div>
            <div class="col-sm-12">
                <div class="writer-info">
                    <div class="profile-area">
                        <div class="profile-info">
                            <div class="nick-box">
                                {% if store.writer.nickname %}{{ store.writer.nickname }}{% else %}{{ store.writer }}{% endif %}
                            </div>
                            <div class="board-info">
                                {{ store.created_dt|date:"Y.m.d h:i"}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row board-body">
            <div class="col-sm-6">
                    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            {% for menu in store.menu_set.all %}
                                <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                                <li data-target="#carouselExampleCaptions" data-slide-to="{{ forloop.counter }}"></li>
                            {% endfor %}
                        </ol>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                {% if store.store_image %}
                                    {% thumbnail store.store_image "300x300" crop="center" as im %}
                                        <img src="{{ im.url }}" class="d-block carousel-image w-100" alt="">
                                    {% endthumbnail %}
                                {% else %}
                                    <img src="{% static 'img/alt_image.png' %}" class="w-100" alt="">
                                {% endif %}
                            </div>
                            {% for menu in store.menu_set.all %}
                                <div class="carousel-item">
                                    {% if menu.food_image %}
                                        {% thumbnail menu.food_image "300x300" crop="center" as im %}
                                            <img src="{{ im.url }}" class="d-block carousel-image w-100" alt="">
                                        {% endthumbnail %}
                                    {% else %}
                                        <img src="{% static 'img/alt_image.png' %}" class="d-block w-100 carousel-image" alt="">
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            <div class="col-sm-6">
                <table class="table">
                        <tbody>
                        <tr>
                            <th style="width: 20%;">설명</th>
                            <td>{{ store.description }}</td>
                        </tr>
                        <tr>
                            <th>주소</th>
                            <td>{{ store.location }}</td>
                        </tr>
                        <tr>
                            <th>연락처</th>
                            <td>{{ store.phone_number }}</td>
                        </tr>
                        <tr>
                            <th>영업시간</th>
                            <td>{{ store.running_time }}</td>
                        </tr>
                        <tr>
                            <th>메뉴</th>
                            <td>
                                {% for menu in store.menu_set.all %}
                                    {{ menu.name }}<br>
                                {% endfor %}
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <div id="map" style="width:100%;height:400px;"></div>
            </div>
        </div>
        <div class="row mt-3 body-footer">
                <div class="col-md-12 mb-3">
                    <div>
                        <b>TAGS</b> <i class="fas fa-tag"></i>
                        {% load taggit_templatetags2_tags %}
                        {% get_tags_for_object object as "tags" %}
                        {% for tag in tags %}
                            <a href="{% url 'helpers:tagged_object_list' tag.name %}">{{ tag.name }}</a>
                        {% endfor %}
                        &emsp;
                        <a href="{% url 'helpers:tag_cloud' %}"><span class="btn btn-info btn-sm">TagCloud</span></a>
                    </div>
                </div>
                <div class="col-md-12">
                    <div>
                        {% if form.errors %}
                            <div class="alert alert-danger">{{ form.errors }}</div>
                        {% endif %}
                        <form action="" method="post" id="multiForm">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.text }}
                            </div>
                            <input id="writeComment" type="submit" value="작성" class="btn btn-primary">
                        </form>
                        <div class="comment-wrapper"></div>
                    </div>
                </div>
            </div>
    </div>
{% endblock %}
{% block extra-script %}
    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey={{ KAKAO_JAVASCRIPT }}&libraries=services"></script>
    <script>
        var mapContainer = document.getElementById('map'), // 지도를 표시할 div
            mapOption = {
                center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
                level: 3 // 지도의 확대 레벨
            };

        // 지도를 생성합니다
        var map = new kakao.maps.Map(mapContainer, mapOption);

        // 주소-좌표 변환 객체를 생성합니다
        var geocoder = new kakao.maps.services.Geocoder();

        // 주소로 좌표를 검색합니다
        geocoder.addressSearch('{{store.location}}', function (result, status) {

            // 정상적으로 검색이 완료됐으면
            if (status === kakao.maps.services.Status.OK) {

                var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

                // 결과값으로 받은 위치를 마커로 표시합니다
                var marker = new kakao.maps.Marker({
                    map: map,
                    position: coords
                });

                // 인포윈도우로 장소에 대한 설명을 표시합니다
                var infowindow = new kakao.maps.InfoWindow({
                    content: `<div style="width:150px;text-align:center;padding:6px 0;">{{store.name}}<br><a href="https://map.kakao.com/link/map/{{store.name}},${coords.Ha},${coords.Ga}" style="color:blue" target="_blank">큰지도보기</a> <a href="https://map.kakao.com/link/to/{{store.name}},33.450701,126.570667" style="color:blue" target="_blank">길찾기</a></div>`
                });
                infowindow.open(map, marker);

                // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
                map.setCenter(coords);
            }
        });
    </script>
    <script>
        var MyGlobal = {
            url: "{% url 'store:like' %}",
            detailUrl: "{{ store.get_absolute_url }}",
            commentListUrl: "{% url 'store:comment' store.slug %}",
            commentCreateUrl: "{% url 'store:comment_create' store.slug %}",
            csrfmiddlewaretoken: '{{ csrf_token }}'
        }
    </script>
    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/detail_page.js' %}"></script>
{% endblock %}