board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.BoardIndex.as_view(), name='index'),
    path('detail/<str:slug>/', views.BoardDetail.as_view(), name='detail'),
    path('detail/<str:slug>/comment/create/', views.comment_create, name='comment_create'),
    path('detail/<str:slug>/comment/', views.CommentListView.as_view(), name='comment'),
    path('detail/<str:slug>/comment/create/', views.comment_create, name='comment_create'),
    path('detail/<str:slug>/comment/update/<int:pk>/', views.comment_update, name='comment_update'),
    path('detail/<str:slug>/comment/delete/<int:pk>/', views.comment_delete, name='comment_delete'),
    path('like/', views.like, name='like'),
    path('post/new/', views.BoardCreateV.as_view(), name='post_add'),
    path('post/edit/<int:pk>/', views.BoardUpdateV.as_view(), name='post_edit'),
    path('post/delete/<int:pk>/', views.BoardDeleteV.as_view(), name='post_delete'),
]

helpers/urls.py
from django.urls import path
from . import views

app_name='helpers'
urlpatterns = [
    path('search/', views.search_word, name='search'),
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from store.models import Store
from board.models import UserBoard

class HomePageView(TemplateView):

    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['store_list'] = Store.objects.filter(category='restaurant')[:1] | \
                                Store.objects.filter(category='bar')[:1] | \
                                Store.objects.filter(category='cafe')[:1]

        return context

urlpatterns = [
    path('board/', include('board.urls')),
    path('store/', include('store.urls')),
    path('helpers/', include('helpers.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomePageView.as_view(), name='home'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
]

if settings.DEBUG:
    if settings.DEBUG:
        import debug_toolbar
        urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.shortcuts import reverse
from taggit.managers import TaggableManager
from django.utils.text import slugify
from django.conf import settings
from django.contrib.auth import get_user_model


def generate_unique_slug(klass, field):
    """
    return unique slug if origin slug is exist.
    """
    origin_slug = slugify(field, allow_unicode=True)
    unique_slug = origin_slug
    numb = 1
    while klass.objects.filter(slug=unique_slug).exists():
        unique_slug = '%s-%d' % (origin_slug, numb)
        numb += 1
    return unique_slug


class UserBoard(models.Model):
    title = models.CharField(max_length=50, blank=True, verbose_name='제목')
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='작성자')
    content = models.TextField(verbose_name='내용')
    created_dt = models.DateTimeField(auto_now_add=True)
    modified_dt = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_boards')
    like_count = models.PositiveIntegerField(default=0)
    tags = TaggableManager(blank=True)

    def __str__(self):
        return '{}-{}'.format(self.writer, self.title)

    def get_absolute_url(self):
        return reverse('board:detail', args=[self.slug])

    def save(self, **kwargs):
        if self.slug:
            if slugify(self.title, allow_unicode=True) != self.slug:
                self.slug = generate_unique_slug(UserBoard, self.title)
        else:
            self.slug = generate_unique_slug(UserBoard, self.title)
        super().save(**kwargs)

    class Meta:
        ordering = ['-created_dt']
        verbose_name = '게시판'
        verbose_name_plural = '게시판'


class Comment(models.Model):
    post = models.ForeignKey(UserBoard, on_delete=models.CASCADE)
    writer = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True, related_name='comments')
    text = models.TextField()
    created_dt = models.DateTimeField(auto_now_add=True)
    modified_dt = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.writer}"

board/forms.py
from django import forms
from .models import UserBoard, Comment


class BoardForm(forms.ModelForm):
    class Meta:
        model = UserBoard
        fields = ('title', 'content')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '제목을 입력해주세요.'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'id': 'post_content', 'placeholder': '내용을 입력해주세요.'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'id': 'inputComment', 'rows': '3', 'style': 'resize:none;'}),
        }

board/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from .models import UserBoard, Comment
from .forms import CommentForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from mysite.views import OwnerOnlyMixin
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin
from django.conf import settings
from django.http import JsonResponse
import json


class BoardIndex(ListView):
    template_name = 'board/index.html'
    context_object_name = 'board_list'
    paginate_by = 10

    def get_queryset(self):
        return UserBoard.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5  # Display only 5 page numbers
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1
        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        return context


class BoardCreateV(LoginRequiredMixin, CreateView):
    model = UserBoard
    fields = ('title', 'content', 'tags')
    success_url = reverse_lazy('board:index')
    template_name = 'board/board_form.html'

    def form_valid(self, form):
        form.instance.writer = self.request.user
        return super().form_valid(form)


class BoardUpdateV(OwnerOnlyMixin, UpdateView):
    model = UserBoard
    fields = ('title', 'content', 'tags')
    template_name = 'board/board_form.html'


class BoardDeleteV(OwnerOnlyMixin, DeleteView):
    model = UserBoard
    success_url = reverse_lazy('board:index')
    template_name = 'board/board_confirm_delete.html'


class CommentListView(ListView):
    model = Comment
    paginate_by = 5
    template_name = '_comment_list.html'
    context_object_name = 'comment_list'

    def get_queryset(self):
        store = get_object_or_404(UserBoard, slug=self.kwargs['slug'])
        return store.comment_set.all()

    def get_context_data(self, *args, **kwargs):
        store = get_object_or_404(UserBoard, slug=self.kwargs['slug'])
        context = super().get_context_data(*args, **kwargs)
        paginator = context['paginator']
        page_numbers_range = 5  # Display only 5 page numbers
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1
        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        context['store'] = store
        return context


@login_required
def comment_create(request, slug):
    if not request.user.is_authenticated:
        return JsonResponse({'authenticated': False})
    post = get_object_or_404(UserBoard, slug=slug)
    form = CommentForm(request.POST)
    if form.is_valid():
        form.instance.writer = request.user
        form.instance.post = post
        form.save()
    paginator = Paginator(post.comment_set.all(), 5)
    last_page = paginator.num_pages
    return JsonResponse({'last_page': last_page, 'authenticated': True})


@login_required
def comment_update(request, slug, pk):
    store = get_object_or_404(UserBoard, slug=slug)
    comment = store.comment_set.get(pk=pk)
    if comment.writer == request.user:
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save()
            html = render_to_string('_comment_update.html', {'comment': comment} )
            return JsonResponse({'is_updated': True, 'html': html})


@login_required
def comment_delete(request, slug, pk):
    store = get_object_or_404(UserBoard, slug=slug)
    comment = store.comment_set.get(pk=pk)
    if comment.writer == request.user:
        comment.delete()
    return JsonResponse({'is_deleted': True})


class BoardDetail(FormMixin, DetailView):
    model = UserBoard
    form_class = CommentForm
    template_name = 'board/detail.html'

    def get_success_url(self):
        return reverse('board:detail', args=[self.object.slug])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        context['comments'] = self.object.comment_set.all()
        return context


@login_required
def like(request):
    pk = request.GET.get('pk', None)
    board = get_object_or_404(UserBoard, pk=pk)

    if request.user in board.like_users.all():
        board.like_users.remove(request.user)
        board.like_count -= 1
        board.save()
        message = False
    else:
        board.like_users.add(request.user)
        board.like_count += 1
        board.save()
        message = True
    context = {
        'like_count': board.like_users.count(),
        'message': message,
        'nickname': request.user.nickname
    }
    return HttpResponse(json.dumps(context), content_type="application/json")

board/templates/board/board_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form action="." method="post">
    {% csrf_token %}
    <p>"{{ object }}"게시글을 삭제하겠습니까?</p>
    <input type="submit" value="삭제" class="btn btn-danger">
</form>
<button class="btn btn-danger" onclick="history.back()">되돌아가기</button>
{% endblock %}

board/templates/board/board_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

<form method="POST" action="">
    {% csrf_token %}
    <div class="form-group">
        {{ form.title|add_label_class:""}}
        {{ form.title|add_class:"form-control" }}
    </div>
    <div class="form-group">
        {{ form.content|add_label_class:"" }}
        {{ form.content|add_class:"form-control"|attr:"id:post_content" }}
    </div>
    <div class="form-group">
        {% load taggit_templatetags2_tags %}
        {{ form.tags|add_label_class:"col-form-label col-sm-3 font-weight-bold" }}
        {{ form.tags|add_class:"form-control" }}
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}

{% block extra-script %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
<script>
    $(document).ready(function() {
        $('#post_content').summernote({
            height: 300
        });
    });
</script>
{% endblock %}

board/templates/board/board_success.html
<script>
    message = "{{ message }}";
    console.log(message);
    alert(message);
    window.location.href = "{% url 'board:index' %}"
</script>

board/templates/board/detail.html
{% extends 'base.html' %}
{% load static %}
{% block extra-style %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<style>
    .board-body{
        min-height: 150px;
    }
</style>
{% endblock %}
{% block content %}
<button class="btn btn-primary mb-3 p-2" onclick="location.href='{% url 'board:post_edit' userboard.pk %}'">수정</button>
<button class="btn btn-primary mb-3 p-2" onclick="location.href='{% url 'board:post_delete' userboard.pk %}'">삭제</button>
<div class="board">
    <div class="row board-header">
        <div class="col-sm-12">
            <div class="float-right text-center">
                <button post-id="{{ userboard.pk }}" class="btn userboard-like">
                    {% if user in userboard.like_users.all %}
                        <i id="like-heart-{{userboard.pk}}" class="fas fa-heart fa-2x"></i></button>
                    {% else %}
                        <i id="like-heart-{{userboard.pk}}" class="far fa-heart fa-2x"></i></button>
                    {% endif %}
                <br>
                <span id="count-{{ userboard.pk }}">{{ userboard.like_users.count }}개</span>
                <span id="like-user-{{ userboard.pk }}"></span>
            </div>
            <div class="h3">{{ userboard.title }}</div>
        </div>
        <div class="col-sm-12">
            <div class="writer-info">
                <div class="profile-area">
                    <div class="profile-info">
                        <div class="nick-box">
                            {% if userboard.writer.nickname %}{{ userboard.writer.nickname }}{% else %}{{ userboard.writer}}{% endif %}
                        </div>
                        <div class="board-info">
                            {{ userboard.created_dt|date:"Y.m.d h:i"}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row board-body">
        <div class="col-md-11">
            {{ userboard.content|safe}}
        </div>
    </div>
    <div class="row mt-3 body-footer">
        <div class="col-md-11 mb-3">
            <div>
                <b>TAGS</b> <i class="fas fa-tag"></i>
                {% load taggit_templatetags2_tags %}
                {% get_tags_for_object object as "tags" %}
                {% for tag in tags %}
                <a href="{% url 'helpers:tagged_object_list' tag.name %}">{{tag.name}}</a>
                {% endfor %}
                &emsp;
                <a href="{% url 'helpers:tag_cloud' %}"><span class="btn btn-info btn-sm">TagCloud</span></a>
            </div>
        </div>
        <div class="col-md-11">
            <div>
                {% if form.errors %}
                    <div class="alert alert-danger">{{ form.errors }}</div>
                {% endif %}
                <form action="" method="post" id="multiForm">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.text }}
                    </div>
                    <input id="writeComment" type="submit" value="작성" class="btn btn-primary">
                </form>
                <div class="comment-wrapper"></div>
            </div>
        </div>
    </div>
</div>
<hr>
{% endblock %}

{% block extra-script %}
<script>
    var MyGlobal = {
        url: "{% url 'board:like' %}",
        detailUrl: "{{ userboard.get_absolute_url }}",
        commentListUrl: "{% url 'board:comment' userboard.slug %}",
        commentCreateUrl: "{% url 'board:comment_create' userboard.slug %}",
        csrfmiddlewaretoken: '{{ csrf_token }}'
    }
</script>
<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
<script type="text/javascript" src="{% static 'js/detail_page.js' %}"></script>
{% endblock %}

board/templates/board/index.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block extra-style %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<style>
    .board-footer {
        text-align: center;
    }
</style>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-11">
        <a class="text-dark" href="{% url 'board:index' %}"><h2 class="title">게시판</h2></a>
        <button type="button" class='btn btn-primary float-right mb-1' onclick="location.href='{% url 'board:post_add' %}'">게시글 작성</button>
    </div>
</div>
<div class="row">
    <div class="col" id="pc">
        <table class="table board-table">
          <thead>
            <tr>
              <th scope="col" style="width: 55%;">제목</th>
              <th scope="col" style="width: 15%;">글쓴이</th>
              <th scope="col" style="width: 10%;">추천</th>
              <th scope="col" style="width: 20%;">날짜</th>
            </tr>
          </thead>
          <tbody>
            {% for item in board_list %}
            <tr>
              <td><a class="text-dark text-truncate" href="{% url 'board:detail' item.slug %}">{{ item.title }}</a>({{ item.comment_set.count }})</td>
              <td class="author">{% if item.writer.nickname %}{{ item.writer.nickname }}{% else %}{{ item.writer }}{% endif %}</td>
              <td class="text-primary voteNum">{{ item.like_count }}</td>
              <td class="time">{{ item.created_dt|naturalday }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
    <div class="col p-0" id="mobile">
        <ul class="list-group">
            {% for item in board_list %}
            <li class="list-group-item p-2 board-item">
                <div style="width:100%;">
                    <div class="text-truncate">
                        <a href="{{item.get_absolute_url}}" class="text-dark font-weight-bold" style="font-size: 13px;">{{item.title}}</a>
                    </div>
                    <div class="d-flex">
                        <div class="flex-fill">
                            <span class="text-primary"><i class="fa fa-thumbs-up" aria-hidden="true"></i> {{item.like_count}}</span>
                            <span>{{item.created_dt|naturalday}}</span>
                        </div>
                        <div class="flex-fill">
                            <div class="d-flex justify-content-end">
                                {% if item.writer.nickname %}{{ item.writer.nickname }}{% else %}{{ item.writer }}{% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
<div class="row mt-5">
    <div class="col board-footer">
        <div class="d-flex justify-content-center">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><span>Prev</span></a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#"><span>Prev</span></a>
                        </li>
                    {% endif %}

                    {% for page in page_range %}
                        <li class="page-item {% if page == page_obj.number %}active{% endif %}">
                            <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                        </li>
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}"><span>Next</span></a>
                        </li>
                    {% else %}
                        <li {% if not page_obj.has_next %}class="page-item disabled"{% endif %}>
                            <a class="page-link" href="#"><span>Next</span></a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}

board/templates/board/post.html
{% extends 'base.html' %}
{% block header %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
<script>
    $(document).ready(function() {
        $('#post_content').summernote({
            height: 300
        });
    });
</script>
{% endblock %}
{% block content %}

<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="btn btn-primary"> Save</button>
</form>
{% endblock %}