accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
	path('login/', views.UserLoginView.as_view(), name='login'),
	path('logout/', views.signout, name='logout'),
	path('signup/', views.UserSignUpView.as_view(), name='signup'),
	path('signup/done/', views.UserSignUpDoneView.as_view(), name='signup_done'),
	path('mypage/', views.MyPageV.as_view(), name='mypage'),
	path('checkuser/', views.check_user, name='check_user'),
	path('checknickname/', views.check_nickname, name='check_nickname'),
	path('finduser/', views.FindUser.as_view(), name='find_user')
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.BoardIndex.as_view(), name='index'),
    path('detail/<str:slug>/', views.BoardDetail.as_view(), name='detail'),
    path('detail/<str:slug>/comment/create/', views.comment_create, name='comment_create'),
    path('detail/<str:slug>/comment/', views.CommentListView.as_view(), name='comment'),
    path('detail/<str:slug>/comment/create/', views.comment_create, name='comment_create'),
    path('detail/<str:slug>/comment/update/<int:pk>/', views.comment_update, name='comment_update'),
    path('detail/<str:slug>/comment/delete/<int:pk>/', views.comment_delete, name='comment_delete'),
    path('like/', views.like, name='like'),
    path('post/new/', views.BoardCreateV.as_view(), name='post_add'),
    path('post/edit/<int:pk>/', views.BoardUpdateV.as_view(), name='post_edit'),
    path('post/delete/<int:pk>/', views.BoardDeleteV.as_view(), name='post_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from store.models import Store
from board.models import UserBoard

class HomePageView(TemplateView):

    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['store_list'] = Store.objects.filter(category='restaurant')[:1] | \
                                Store.objects.filter(category='bar')[:1] | \
                                Store.objects.filter(category='cafe')[:1]

        return context

urlpatterns = [
    path('board/', include('board.urls')),
    path('store/', include('store.urls')),
    path('helpers/', include('helpers.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomePageView.as_view(), name='home'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
]

if settings.DEBUG:
    if settings.DEBUG:
        import debug_toolbar
        urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(max_length=254, unique=True, verbose_name='이메일')
    nickname = models.CharField(max_length=30, unique=True, verbose_name='닉네임')
    phone_number = models.CharField(max_length=30, unique=True, verbose_name='전화번호')

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from accounts.models import User


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('email', 'nickname', 'phone_number', )


class FindUserForm(forms.Form):
    nickname = forms.CharField(max_length=30, label='닉네임', widget=forms.TextInput(attrs=
                                                                                  {'placeholder': '닉네임을 입력해주세요.',
                                                                                   'class': 'form-control',
                                                                                   'autofocus': 'autofocus'}))
    phone_number = forms.CharField(max_length=30, label='전화번호', widget=forms.TextInput(attrs=
                                                                                       {'placeholder': '전화번호를 입력해주세요.',
                                                                                        'class': 'form-control'}))

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http.response import HttpResponseRedirect
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse

import json
from django.http import HttpResponse

from django.views.generic import TemplateView, CreateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import get_user_model
from django.contrib.auth import views as auth_views
from .forms import CustomUserCreationForm, FindUserForm

from django.contrib.auth import logout # 로그아웃 처리하기 위해 선언


def check_user(request):
    cUser = get_user_model()
    if not cUser.objects.filter(username=request.POST.get('user_name')).exists():
        print('possible')
        context = {'msg': True}
    else:
        print('impossible')
        context = {'msg': False}
    return HttpResponse(json.dumps(context), content_type="application/json")


def check_nickname(request):
    cUser = get_user_model()
    if not cUser.objects.filter(nickname=request.GET.get('user_nickname')).exists():
        print('possible')
        context = {'msg': True}
    else:
        print('impossible')
        context = {'msg': False}
    return HttpResponse(json.dumps(context), content_type="application/json")


class FindUser(FormView):
    form_class = FindUserForm
    template_name = 'accounts/find_user.html'

    def form_valid(self, form):
        nickname = form.cleaned_data['nickname']
        phone_number = form.cleaned_data['phone_number']
        cUser = get_user_model()
        context = {}
        try:
            user = cUser.objects.get(nickname=nickname, phone_number=phone_number)
        except ObjectDoesNotExist:
            context['error'] = '일치하는 아이디가 없습니다.'
        else:
            context['username'] = user.username
        return render(self.request, 'accounts/find_user_done.html', context=context)


class UserLoginView(auth_views.LoginView):
    template_name = 'accounts/signin.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse('home'))
        return super().dispatch(request, *args, **kwargs)


class UserSignUpView(CreateView):
    template_name = 'accounts/signup.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('accounts:signup_done')


class UserSignUpDoneView(TemplateView):
    template_name = 'accounts/signup_done.html'


class MyPageV(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/mypage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cUser = get_user_model()
        u = cUser.objects.get(username=self.request.user)
        context['mylists'] = u.userboard_set.all()
        return context


def signout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

accounts/templates/accounts/find_user.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<a href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" alt="" class="mainLogo mb-5"></a>
{{ form.errors }}
<div class="row">
    <div class="col">
        <form action="" method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field.label }}
                {{ field }}
            </div>
            {% endfor %}
            <input type="submit" value="찾기" class="btn btn-primary">
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/find_user_done.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<a href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" alt="" class="mainLogo mb-5"></a>
<div class="row">
    <div class="col">
        <div>
            <div>
                {% if error %}
                <div class="h1">Not Found..</div>
                    <div class="alert alert-danger">{{ error }}</div>
                    <a href="{% url 'accounts:find_user' %}" class="font-weight-bold">아이디 찾기</a>
                {% else %}
                <div class="h1">Found it!</div>
                    <div class="alert alert-success">{{ username }}</div>
                    <a href="{% url 'password_reset' %}" class="font-weight-bold">비밀번호 찾기</a>
                {% endif %}
                <span>/ </span><a href="{% url 'accounts:login' %}" class="font-weight-bold">로그인 하기</a></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/mypage.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#iLiked">좋아요 누른 글</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#iWrote">내가 쓴 글</a>
    </li>
</ul>
<div class="tab-content">
    <div class="tab-pane fade show active" id="iLiked">
        <table class="table board-table">
            <thead>
              <tr>
                <th style="width: 60%;">제목</th>
                <th style="width: 40%;">작성날짜</th>
              </tr>
            </thead>
            <tbody>
                {% for item in user.like_stores.all %}
                <tr>
                    <td><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></td>
                    <td>{{ item.created_dt|naturalday}}</td>
                </tr>
                {% endfor %}
                {% for item in user.like_boards.all %}
                <tr>
                    <td><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></td>
                    <td>{{ item.created_dt|naturalday }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="iWrote">
        <table class="table board-table">
            <thead>
              <tr>
                <th style="width: 60%;">제목</th>
                <th style="width: 40%;">작성날짜</th>
              </tr>
            </thead>
            <tbody>
              {% for item in mylists %}
                <tr>
                  <td><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></td>
                  <td>{{ item.created_dt|naturalday }}</td>
                </tr>
              {% endfor %}
            </tbody>
        </table>
        <div class="float-right">
            <a href="{% url 'board:post_add' %}" class="btn btn-primary">게시판 글쓰기</a>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signin.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}로그인 {% endblock %}
{% block main_logo %}{% endblock %}
{% block content %}


<a href="{% url 'home' %}"><img src="/static/img/logo.png" class="mainLogo mb-5"></a>
{% if form.errors %}
	<div class="alert alert-danger">아이디 또는 패스워드를 확인해주세요.</div>
{% endif %}
<div class="row">
	<div class="col-12">
		<form action="" method="POST">
			{% csrf_token %}
			<div class="form-group">
				<label for="userID">아이디</label>
				{{ form.username|add_class:"form-control"|attr:"placeholder:아이디를 입력해주세요." }}
			</div>
			<div class="form-group">
				<label for="userPW">비밀번호</label>
				{{ form.password|add_class:"form-control"|attr:"placeholder:비밀번호 입력해주세요." }}
			</div>
			<div class="d-flex justify-content-center">
				<button type="submit" class="btn btn-outline-primary">로그인</button>
			</div>
			<input type="hidden" name="next" value="{{ next }}">
		</form>
	</div>
</div>
<hr>
<div class="row text-center">
	<a class="col" href="{% url 'accounts:signup' %}">회원가입</a>
	<a class="col" href="{% url 'accounts:find_user' %}">아이디 찾기</a>
	<a class="col" href="{% url 'password_reset' %}">비밀번호 찾기</a>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %} 회원가입 {% endblock %}
{% block main_logo %}{% endblock %}
{% block jscode %}
<script src="https://code.jquery.com/jquery-1.12.4.js" crossorigin="anonymous"></script>
<script src="{% static 'js/sign.js' %}"></script>
{% endblock %}
{% block content %}
<a href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" class="mainLogo mb-5"></a>

{% if form.errors %}
    {% for field in form %}
        {% for ferror in field.errors %}
            <div class="alert alert-danger">{{ ferror }}</div>
        {% endfor %}
    {% endfor %}
{% endif %}

{% if error %}
	<div class="alert alert-danger">{{error}}</div>
{% endif %}
<form action="" method="POST">
	{% csrf_token %}
	<div class="form-group">
		<label class="col-form-label" for="id">아이디</label>
		{{ form.username|add_class:"form-control"}}
	</div>
	<div id="check-user"></div>
	<div class="form-group">
		<label class="col-form-label" for="nickname">닉네임</label>
		{{ form.nickname|add_class:"form-control" }}
	</div>
	<div id="check-nickname"></div>
	<div class="form-group">
		<label class="col-form-label" for="phonenumber">전화번호</label>
		{{ form.phone_number|add_class:"form-control" }}
	</div>
	<div class="form-group">
		<label class="col-form-label" for="email">이메일</label>
		{{ form.email|add_class:"form-control" }}
	</div>
	<div class="form-group">
		<label class="col-form-label" for="password">패스워드</label>
		{{ form.password1|add_class:"form-control" }}
	</div>
	<div>
		<label class="col-form-label" for="re-password">재확인</label>
		{{ form.password2|add_class:"form-control" }}
	</div>
	<div class="alert alert-success" id="alert-success">비밀번호가 일치합니다.</div>
	<div class="alert alert-danger" id="alert-danger">비밀번호가 일치하지 않습니다.</div>
	<div class="d-flex justify-content-center mt-3">
		<button type="submit" class="btn btn-outline-primary">회원가입</button>
	</div>
</form>
 {% endblock %}

{% block extra-script %}
<script type="text/javascript">
	$(function(){
		$('#alert-success').hide();
		$('#alert-danger').hide();
		$("#id_password2").keyup(function(){
			var pwd1=$('#id_password1').val();
			var pwd2=$('#id_password2').val();
			if(pwd1 != "" || pwd2 != ""){
				if(pwd1 == pwd2){
					$("#alert-success").show();
					$("#alert-danger").hide();
				}else{
					$("#alert-success").hide();
					$("#alert-danger").show();
				}
			}
		});
	});
	// ID 조회하는 기능
	$("#id_username").keyup(function(){
		var userName = $(this).val();
		if(userName) {
			$.ajax({
				type: "POST",
				url: "{% url 'accounts:check_user' %}",
				data: {"user_name": userName, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
				dataType: "json",
				success: function (data) {
					if (data.msg) {
						$('#check-user').removeClass('alert alert-danger').addClass('alert alert-success').text('사용가능합니다.');
					} else {
						$('#check-user').removeClass('alert alert-success').addClass('alert alert-danger').text('사용불가합니다.');
					}
				},
				error: function (request, status, error) {

				},
			})
		} else {
			$('#check-user').removeClass('alert alert-success alert-danger').text(' ');
		}
	});
	// 닉네임 조회하는 기능
	$("#id_nickname").keyup(function(){
		var nickName = $(this).val();
		if(nickName) {
			$.ajax({
				type: "GET",
				url: "{% url 'accounts:check_nickname' %}",
				data: {"user_nickname": nickName },
				dataType: "json",
				success: function (data) {
					if (data.msg) {
						$('#check-nickname').removeClass('alert alert-danger').addClass('alert alert-success').text('사용가능합니다.');
					} else {
						$('#check-nickname').removeClass('alert alert-success').addClass('alert alert-danger').text('사용불가합니다.');
					}
				},
				error: function (request, status, error) {

				},
			})
		} else {
			$('#check-nickname').removeClass('alert alert-success alert-danger').text(' ');
		}
	});
</script>
{% endblock %}

accounts/templates/accounts/signup_done.html
{% extends 'base.html' %}
{% load static %}

{% block title %} 환영합니다 {% endblock %}
{% block main_logo %}{% endblock %}
{% block content %}
	<div class="">
		<div class="col-sm-12">
			<div class="d-flex justify-content-center">
				<div>
					<p>안녕하세요! 동국대 <span style="color:#ffbf64;">맛을</span> 찾다
						<span style="color:#ff690e;font-weight:bold;font-size:25px;">동국 푸드</span>입니다.</p>
					<p>회원가입 해주셔서 감사합니다!
					<a href="{% url 'accounts:login' %}" class="font-weight-bold">로그인 하기</a></p>
				</div>
			</div>
			<div class="d-flex justify-content-center">
				<img class="mainLogo" src="{% static 'img/signFin.png' %}">
			</div>
		</div>
	</div>
{% endblock %}