accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
	path('login/', views.UserLoginView.as_view(), name='login'),
	path('logout/', views.signout, name='logout'),
	path('signup/', views.UserSignUpView.as_view(), name='signup'),
	path('signup/done/', views.UserSignUpDoneView.as_view(), name='signup_done'),
	path('mypage/', views.MyPageV.as_view(), name='mypage'),
	path('checkuser/', views.check_user, name='check_user'),
	path('checknickname/', views.check_nickname, name='check_nickname'),
	path('finduser/', views.FindUser.as_view(), name='find_user')
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.BoardIndex.as_view(), name='index'),
    path('detail/<str:slug>/', views.BoardDetail.as_view(), name='detail'),
    path('detail/<str:slug>/comment/create/', views.comment_create, name='comment_create'),
    path('detail/<str:slug>/comment/', views.CommentListView.as_view(), name='comment'),
    path('detail/<str:slug>/comment/create/', views.comment_create, name='comment_create'),
    path('detail/<str:slug>/comment/update/<int:pk>/', views.comment_update, name='comment_update'),
    path('detail/<str:slug>/comment/delete/<int:pk>/', views.comment_delete, name='comment_delete'),
    path('like/', views.like, name='like'),
    path('post/new/', views.BoardCreateV.as_view(), name='post_add'),
    path('post/edit/<int:pk>/', views.BoardUpdateV.as_view(), name='post_edit'),
    path('post/delete/<int:pk>/', views.BoardDeleteV.as_view(), name='post_delete'),
]

helpers/urls.py
from django.urls import path
from . import views

app_name='helpers'
urlpatterns = [
    path('search/', views.search_word, name='search'),
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from store.models import Store
from board.models import UserBoard

class HomePageView(TemplateView):

    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['store_list'] = Store.objects.filter(category='restaurant')[:1] | \
                                Store.objects.filter(category='bar')[:1] | \
                                Store.objects.filter(category='cafe')[:1]

        return context

urlpatterns = [
    path('board/', include('board.urls')),
    path('store/', include('store.urls')),
    path('helpers/', include('helpers.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomePageView.as_view(), name='home'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
]

if settings.DEBUG:
    if settings.DEBUG:
        import debug_toolbar
        urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.StoreIndexView.as_view(), name='index'),
    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),
    path('like/', views.like, name='like'),
    path('detail/<str:slug>/', views.StoreDetailView.as_view(), name='detail'),
    path('detail/<str:slug>/comment/', views.CommentListView.as_view(), name='comment'),
    path('detail/<str:slug>/comment/create/', views.comment_create, name='comment_create'),
    path('detail/<str:slug>/comment/update/<int:pk>/', views.comment_update, name='comment_update'),
    path('detail/<str:slug>/comment/delete/<int:pk>/', views.comment_delete, name='comment_delete'),
    path('create/', views.StoreCreateView.as_view(), name='store_add'),
    path('edit/<int:pk>/', views.StoreEditView.as_view(), name='store_edit'),
    path('delete/<int:pk>/', views.StoreDeleteView.as_view(), name='store_delete'),
]

board/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.shortcuts import reverse
from taggit.managers import TaggableManager
from django.utils.text import slugify
from django.conf import settings
from django.contrib.auth import get_user_model


def generate_unique_slug(klass, field):
    """
    return unique slug if origin slug is exist.
    """
    origin_slug = slugify(field, allow_unicode=True)
    unique_slug = origin_slug
    numb = 1
    while klass.objects.filter(slug=unique_slug).exists():
        unique_slug = '%s-%d' % (origin_slug, numb)
        numb += 1
    return unique_slug


class UserBoard(models.Model):
    title = models.CharField(max_length=50, blank=True, verbose_name='제목')
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='작성자')
    content = models.TextField(verbose_name='내용')
    created_dt = models.DateTimeField(auto_now_add=True)
    modified_dt = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_boards')
    like_count = models.PositiveIntegerField(default=0)
    tags = TaggableManager(blank=True)

    def __str__(self):
        return '{}-{}'.format(self.writer, self.title)

    def get_absolute_url(self):
        return reverse('board:detail', args=[self.slug])

    def save(self, **kwargs):
        if self.slug:
            if slugify(self.title, allow_unicode=True) != self.slug:
                self.slug = generate_unique_slug(UserBoard, self.title)
        else:
            self.slug = generate_unique_slug(UserBoard, self.title)
        super().save(**kwargs)

    class Meta:
        ordering = ['-created_dt']
        verbose_name = '게시판'
        verbose_name_plural = '게시판'


class Comment(models.Model):
    post = models.ForeignKey(UserBoard, on_delete=models.CASCADE)
    writer = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True, related_name='comments')
    text = models.TextField()
    created_dt = models.DateTimeField(auto_now_add=True)
    modified_dt = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.writer}"

templates/_comment.html
{% load humanize %}
<div class="comment-area" id="{{ comment.pk }}">
    <div class="comment-box">
        <div class="comment-nick-box">
            <a class="comment-nickname" href="#">{% firstof comment.writer.nickname comment.writer %}</a>
        </div>
        <div class="comment-text-box">
            <p class="comment-text-view">
                <span class="text-comment">{{ comment.text }}</span>
            </p>
        </div>
        <div class="comment-info-box">{{ comment.created_dt }}</div>
        <div class="comment_tool">
            <a href="javascript:void(0)" class="update-comment">수정</a>
            <a href="javascript:void(0)" class="delete-comment" onclick="deleteComment(this)">삭제</a>
        </div>
    </div>
</div>

templates/_comment_list.html
<div class="comment-list">
    {% for comment in comment_list %}
        <div class="comment-area" id="{{ comment.pk }}">
            <div class="comment-box">
                <div class="comment-nick-box"><a class="comment-nickname" href="#">{% firstof comment.writer.nickname comment.writer %}</a></div>
                <div class="comment-text-box">
                    <p class="comment-text-view">
                        <span class="text-comment">{{ comment.text }}</span>
                    </p>
                </div>
                <div class="comment-info-box">{{ comment.created_dt }}</div>
                <div class="comment_tool">
                    {% if comment.writer == request.user %}
                        <a href="javascript:void(0)" class="update-comment">수정</a>
                        <a href="javascript:void(0)" class="delete-comment" onclick="deleteComment(this)">삭제</a>
                    {% endif %}
                </div>
            </div>
        </div>
    {% empty %}
        댓글이 없습니다.
    {% endfor %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <button class="page-link" onclick=getPage({{ page_obj.previous_page_number }})><span>Prev</span></button>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#"><span>Prev</span></a>
                </li>
            {% endif %}

            {% for page in page_range %}
                <li class="page-item {% if page == page_obj.number %}active{% endif %}">
                    <button class="page-link" onclick=getPage({{ page }})>{{ page }}</button>
                </li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <button class="page-link" onclick=getPage({{ page_obj.next_page_number }})><span>Next</span></button>
                </li>
            {% else %}
                <li {% if not page_obj.has_next %}class="page-item disabled"{% endif %}>
                    <a class="page-link" href="#"><span>Next</span></a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>

templates/_comment_update.html
{% load humanize %}
<div class="comment-box">
    <div class="comment-nick-box"><a class="comment-nickname" href="#">{% firstof comment.writer.nickname comment.writer %}</a></div>
    <div class="comment-text-box">
        <p class="comment-text-view">
            <span class="text-comment">{{ comment.text }}</span>
        </p>
    </div>
    <div class="comment-info-box">{{ comment.created_dt }}</div>
    <div class="comment_tool">
        <a href="javascript:void(0)" class="update-comment">수정</a>
        <a href="javascript:void(0)" class="delete-comment" onclick="deleteComment(this)">삭제</a>
    </div>
</div>

templates/_footer.html
<footer class="footer">
    <div class="inner">
        <div class="dg_logo">
            <a href="/" class="btn-dg"></a>
            <p class="subtitle"></p>
        </div>
        <div class="language-copyrights">
            <small>
                <p>
                    동국푸드<br>제작자: Hong Seok Ju(홍석주)<br>
                    <span class="copyrights">© 2020 DonggukFood by 홍석주 .</span>
                </p>
            </small>
        </div>
    </div>
</footer>

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block extra-style %}
<style>
span.text-primary {
    color: #EE6F1B !important;
}
</style>
{% endblock %}
{% block content %}
<!-- About-->
<div class="raw">
    <h1 class="mb-0">
        Dongguk
        <span class="text-primary">Food</span>
    </h1>
    <div class="subheading mb-5">
    </div>
    <p class="lead mb-5">동국대 주변 음식집 소개와 게시판을 이용할 수 있는 사이트입니다.</p>
</div>
<hr class="m-0"/>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Dongguk Food{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block extra-style %}
    {% endblock %}

</head>
<body>
{% block header %}{% endblock %}
<nav id="nav-top" class="navbar navbar-expand-xl navbar-light fixed-top {% block main_header %}{% endblock %}">
    <span class="navbar-brand mx-5 mb-0 font-weight-bold"><a class="header-title" href="{% url 'home' %}">Dongguk Food</a></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn">
                <a class="nav-link header-text" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item mx-1 btn">
                <a class="nav-link header-text" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item dropdown mx-1 btn">
                <a class="nav-link dropdown-toggle header-text" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    가게보기
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'store:index' %}">전체보기</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'store:category' 'restaurant' %}">음식집</a>
                    <a class="dropdown-item" href="{% url 'store:category' 'bar' %}">술 집</a>
                    <a class="dropdown-item" href="{% url 'store:category' 'cafe' %}">카 페</a>
                </div>
            </li>
            <li class="nav-item mx-1 btn">
                <a class="nav-link header-text" href="{% url 'board:index' %}">게시판</a>
            </li>
            <li class="nav-item mx-1 btn">
                <a class="nav-link header-text" href="{% url 'helpers:tag_cloud' %}">태그</a>
            </li>
        </ul>
        {% block form_area %}
            <form class="form-inline my-2 my-lg-0" style="justify-content: center" action="/helpers/search/" method="post">
                {% csrf_token %}
                <input class="form-control" type="text" name="q" value="" placeholder="검색" style="width: 70%" />
                <input type="submit" value="검색" placeholder="입력" class="btn btn-primary my-2 my-sm-0" />
            </form>
        {% endblock %}
        <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1 btn">
                {% if user.is_active %}
                    <a class="nav-link dropdown-toggle header-text" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;{% firstof user.nickname user.get_username %}님
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'accounts:mypage' %}">마이페이지</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">패스워드 변경</a>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                        {% comment %}
                            <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                        {% endcomment %}
                    </div>
                {% else %}
                    <a class="nav-link dropdown-toggle header-text" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;로그인 해주세요&ensp;
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'accounts:login' %}">로그인</a>
                        <a class="dropdown-item" href="{% url 'accounts:find_user' %}">아이디 찾기</a>
                        <a class="dropdown-item" href="{% url 'password_reset' %}">패스워드 찾기</a>
                        <a class="dropdown-item" href="{% url 'accounts:signup' %}">회원가입</a>
                    </div>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

<div class="container {% block container_class %}{% endblock %}">
    {% block content %}{% endblock %}
</div>

{% include "_footer.html" %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://kit.fontawesome.com/c998a172fe.js"></script>
{% block extra-script %}{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load sorl_thumbnail %}

{% block extra-style %}
<style>
.card-img-top {
    width: 100%;
    height: 15vw;
    object-fit: cover;
}
</style>
{% endblock %}
{% block main_header %}trans-mode{% endblock %}
{% block header %}
    <header class="main-header" style="background-image: url('https://mp-seoul-image-production-s3.mangoplate.com/0776fea76b4a824ff583128cb51dd45c.jpg');">
        <div>
            <p class="title">동국대생들의 맛집 창고</p>
            <h1 class="title">동국 푸드</h1>

            <fieldset class="main-search">
                <legend>전체 검색</legend>

                <label class="search-word" for="main-search">
                    <span class="icon">검색 :</span>
                    <input id="main-search" class="HomeSearchInput" name="main-search" type="text" maxlength="50" placeholder="지역, 식당 또는 음식" autocomplete="off">
                </label>

                <input class="btn-search" type="submit" value="검색" onclick="trackEvent();">
            </fieldset>
        </div>
    </header>
{% endblock %}
{% block container_class %}homepage{% endblock %}
{% block form_area %}{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm">
    <h2 class="title">맛집 리스트</h2>
        <div class="d-flex flex-row-reverse mb-5">
            <a class="float-right text-muted" href="{% url 'store:index' %}">전체 보기</a>
        </div>
        <div class="row">
        {% for store in store_list %}
            <div class="col-sm-4 mb-3">
                <div class="card">
                    {% if store.menu_set.first.food_image %}
                        {% thumbnail store.menu_set.first.food_image "348x255" crop="center" as im %}
                        <img class="card-img-top" src="{{ im.url }}" alt="" style="width: 100%; height: 255px;">
                        {% endthumbnail %}
                    {% else %}
                        <img class="card-img-top" src="{% static 'img/alt_image.png' %}" style="width:100%; height: 255px;">>
                    {% endif %}
                    <div class="card-body text-center">
    <!--                    <h5 class="card-title text-center">{{ store.name }}</h5>-->
                        <h5 class="card-title text-center">
                        {% if store.category == "restaurant" %}
                            음식집
                        </h5>
                        <p class="card-text" style="height: 50px;">
                            맛있는 음식들을 소개해드립니다!
                        </p>
                        {% elif store.category == "bar" %}
                            술집
                        </h5>
                        <p class="card-text" style="height: 50px;">
                            분위기 좋은 술집들을 소개해드립니다!
                        </p>
                        {% else %}
                            카페
                        </h5>
                        <p class="card-text" style="height: 50px;">
                            달콤하고 맛있는 디저트들을 소개해드립니다!
                        </p>
                        {% endif %}
                        <a href="{% url 'store:category' store.category %}" class="btn btn-primary">더보기</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
    <div id="resultarea">

    </div>
{% endblock %}
{% block extra-script %}
<script>
    var isMobile = {
		Android: function() {
			return navigator.userAgent.match(/Android/i);
		},
			BlackBerry: function() {
			  return navigator.userAgent.match(/BlackBerry/i);
		},
			iOS: function() {
			  return navigator.userAgent.match(/iPhone|iPad|iPod/i);
		},
			Opera: function() {
			  return navigator.userAgent.match(/Opera Mini/i);
		},
			Windows: function() {
	      return navigator.userAgent.match(/IEMobile/i);
		},
			any: function() {
			return (isMobile.Android() || isMobile.BlackBerry() || isMobile.iOS() || isMobile.Opera() || isMobile.Windows());
		}
	};

    function submitForm(value){
        if (!value.length) {
            alert('내용을 입력해주세요!');
        } else {
            var form = document.createElement('form');
            var objs1;
            var objs2;
            objs1 = document.createElement('input');
            objs1.setAttribute('type', 'hidden');
            objs1.setAttribute('name', 'csrfmiddlewaretoken');
            objs1.setAttribute('value', '{{ csrf_token }}');
            objs2 = document.createElement('input');
            objs2.setAttribute('type', 'input');
            objs2.setAttribute('name', 'q');
            objs2.setAttribute('value', value);
            form.appendChild(objs1);
            form.appendChild(objs2);
            form.setAttribute('method', 'post');
            form.setAttribute('action', "/helpers/search/");
            document.body.appendChild(form);
            form.submit();
            form.remove();
        }
    }
    function trackEvent(){
        var value = $('#main-search').val();
        submitForm(value)
    }
    $(document).ready(function () {
        //스크롤 발생 이벤트 처리
        if (!isMobile.any()) {
            $(window).scroll(function () {
                const scrollT = $(this).scrollTop();
                const scrollH = $('.main-header').outerHeight() * 0.8; //스크롤바의 상단위치
                if (scrollT < scrollH) { // 스크롤바가 아래 쪽에 위치할 때
                    $('#nav-top').addClass('trans-mode');
                } else {
                    $('#nav-top').removeClass('trans-mode');
                }
            });
        } else {
            $('#nav-top').removeClass('trans-mode');
        }
        $('#main-search').keydown(function(e){
            if(e.keyCode === 13){
                var value = e.target.value
                submitForm(value);
            }
        });
    });
</script>
{% endblock %}